org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true
systemProp.socksProxyHost=127.0.0.1
systemProp.socksProxyPort=10808
systemProp.socksNonProxyHosts=localhost|127.0.0.1|[::1]
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=34

android.suppressUnsupportedCompileSdk=34,35
org.gradle.java.home=C:/Program Files/Android/Android Studio/jbr
org.gradle.java.installations.paths=C:/Program Files/Android/Android Studio/jbr
org.gradle.java.home=C:/Program Files/Android/Android Studio/jbr
