package com.mlmvpn.scanner.engines.vpngate

import com.tim.openvpn.configuration.OpenVPNConfig

/**
 * Small, pure fixes applied to a VPN Gate .ovpn before it reaches the OpenVPN parser.
 *
 * VPN Gate profiles are generated by SoftEther and are already complete — inline `<ca>`,
 * `<cert>` and `<key>` blocks, `proto tcp`, port 1194, AES-128-CBC. We only append a few
 * directives that make an unattended mobile connect behave, and never rewrite what's there.
 */
object OvpnProfileBuilder {

    private val RE_REMOTE = Regex("""^\s*remote\s+(\S+)\s+(\d+)""", RegexOption.MULTILINE)

    /** The endpoint the core will dial, for logging and latency probes. */
    fun remoteOf(ovpn: String): Pair<String, Int>? =
        RE_REMOTE.find(ovpn)?.let { m ->
            val port = m.groupValues[2].toIntOrNull() ?: return null
            m.groupValues[1] to port
        }

    private val RE_PROTO = Regex("""^\s*proto\s+(\S+)""", RegexOption.MULTILINE)
    private val RE_CIPHER = Regex("""^\s*cipher\s+(\S+)""", RegexOption.MULTILINE)
    private val RE_AUTH = Regex("""^\s*auth\s+(\S+)""", RegexOption.MULTILINE)

    /**
     * Turns a VPN Gate profile into the field-based [OpenVPNConfig] the library is built
     * around, so `buildConfig()` emits the config instead of us handing openvpn3 the raw
     * SoftEther file.
     *
     * The reason is `proto tcp`. That is OpenVPN 2 syntax; openvpn3 expects the direction to
     * be explicit, and `buildConfig()` writes it as `remote <host> <port> tcp-client`. Passing
     * the SoftEther text verbatim left the core cycling through 10-second connect attempts
     * that never reached the TLS stage — even though a hand-rolled OpenVPN hard-reset to the
     * same endpoint gets a proper HARD_RESET_SERVER back, so the path itself is fine.
     *
     * Returns null when a required piece is missing, so the caller can fall back to the raw
     * profile rather than dial a half-built config.
     */
    fun toConfig(ovpn: String, name: String): OpenVPNConfig? {
        val text = ovpn.lines().joinToString("\n")

        val remote = RE_REMOTE.find(text) ?: return null
        val host = remote.groupValues[1]
        val port = remote.groupValues[2].toIntOrNull() ?: return null

        // openvpn3 wants the role, not just the transport.
        val type = when (RE_PROTO.find(text)?.groupValues?.get(1)?.lowercase()) {
            "udp", "udp-client" -> "udp"
            else -> "tcp-client"
        }

        val ca = inlineBlock(text, "ca") ?: return null
        val cert = inlineBlock(text, "cert") ?: return null
        val key = inlineBlock(text, "key") ?: return null

        return OpenVPNConfig(
            name = name,
            host = host,
            port = port,
            type = type,
            cipher = RE_CIPHER.find(text)?.groupValues?.get(1) ?: "AES-128-CBC",
            auth = RE_AUTH.find(text)?.groupValues?.get(1) ?: "SHA1",
            ca = ca,
            key = key,
            cert = cert,
            tlsCrypt = "",
            configuration = null,
        )
    }

    /**
     * The whole `<tag> … </tag>` block, tags included — that is what `buildConfig()` appends
     * verbatim. Unlike the library's own parser this returns null instead of crashing when the
     * block is absent, which is the normal case for `<tls-crypt>` in VPN Gate profiles.
     */
    private fun inlineBlock(text: String, tag: String): String? {
        val open = text.indexOf("<$tag>")
        if (open < 0) return null
        val close = text.indexOf("</$tag>", open)
        if (close < 0) return null
        return text.substring(open, close + "</$tag>".length)
    }

    /** The public credentials VPN Gate documents for every one of its relays. */
    const val USERNAME = "vpn"
    const val PASSWORD = "vpn"

    private val EXTRA_DIRECTIVES = listOf(
        "persist-tun",
        "nobind",
        "connect-retry 2 30",
        "resolv-retry 5",
        // Required by the CLIENT certificate, not the server's.
        //
        // Every VPN Gate profile carries the same 2013 dummy client keypair, signed with
        // sha1WithRSAEncryption. openvpn3 defaults to `tls-cert-profile preferred`, which
        // refuses SHA-1, so when the server sends its CertificateRequest the handshake simply
        // stops — reproducibly, on volunteer boxes and on the project's own port-443 relays
        // alike, always immediately after the server chain verifies.
        //
        // The "VERIFY OK … RSA-SHA256" lines in the core log describe the SERVER chain and say
        // nothing about the client cert; reading them as an all-clear is what made this look
        // ruled out earlier.
        "tls-cert-profile insecure",
        // These servers complete a TLS 1.3 handshake and stall on TLS 1.2.
        //
        // Measured with a standalone OpenVPN control-channel client on the SAME Wi-Fi as the
        // phone (PC 192.168.1.153, phone 192.168.1.138): letting it negotiate freely it picks
        // TLS 1.3 and completes 8 times out of 8, client certificate included. Forcing TLS 1.2
        // makes the server go silent right after the client's Finished — the exact point, and
        // the exact symptom, at which openvpn3 gives up on the phone.
        "tls-version-min 1.3",
        // The tunnel comes all the way up — PUSH_REPLY, ASSIGN_IP, "TUN established" — and then
        // dies on "crypto_alg: AES-128-CBC: bad cipher for data channel use": with IV_NCP=2 the
        // core only accepts AEAD on the data channel, while SoftEther's OpenVPN emulation
        // offers CBC exclusively.
        //
        // `ncp-disable` is the OpenVPN 2 spelling and this core rejects the whole profile for
        // it ("Removed deprecated option"). These two are the supported equivalents — both are
        // present as recognised option strings in libovpn3.so.
        "data-ciphers-fallback AES-128-CBC",
        "compat-mode 2.4.0",
    )

    /**
     * Normalises line endings, appends the directives above (skipping any the profile already
     * sets), and inlines the public credentials.
     *
     * The CRLF normalisation is NOT cosmetic. VPN Gate profiles are CRLF throughout (211 of
     * them in a typical 9 KB profile), and OpenVPNConfigParser splits on '\n' only, so every
     * token keeps a trailing '\r'. Nothing then matches — the whole file logs as "Unknown
     * config param", `<ca>` is never found, and `linesByKey` crashes with
     * `IndexOutOfBoundsException: fromIndex = -1`.
     */
    fun harden(ovpn: String): String {
        val lines = ovpn.lines()

        val present = lines
            .map { it.trim() }
            .filter { it.isNotEmpty() && !it.startsWith("#") && !it.startsWith(";") }
            .map { it.substringBefore(' ') }
            .toSet()

        // Credentials go in unconditionally, not only when the profile asks.
        //
        // VPN Gate ships `#auth-user-pass` commented out, so openvpn3's eval_config reports
        // autologin=true and dials with "UsernameEmpty/PasswordEmpty". The servers do want
        // credentials: TLS completes, the certificate chain verifies at every depth, and then
        // the server simply stops answering until the session dies with KEEPALIVE_TIMEOUT.
        // VPN Gate's own instructions are to use vpn/vpn whenever a client asks for them.

        // Rejoining the split lines with '\n' is what strips the CR. The filter additionally
        // drops any bare directive before inlining: OpenVPN rejects the same option twice, and
        // `auth-user-pass` plus an `<auth-user-pass>` block is exactly that.
        val body = lines
            .filterNot { it.trim() == "auth-user-pass" }
            // `proto tcp` is OpenVPN 2 syntax; openvpn3 wants the role spelled out.
            .map { if (it.trim() == "proto tcp") "proto tcp-client" else it }
            .joinToString("\n")

        val sb = StringBuilder(body)
        if (!body.endsWith("\n")) sb.append('\n')

        for (directive in EXTRA_DIRECTIVES) {
            if (directive.substringBefore(' ') !in present) sb.append(directive).append('\n')
        }

        sb.append("<auth-user-pass>\n")
            .append(USERNAME).append('\n')
            .append(PASSWORD).append('\n')
            .append("</auth-user-pass>\n")

        return sb.toString()
    }
}
